<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<div class="row">
    <!--
<a href="#" id="show-reviews"><?php echo __('Show Reviews')?></a>-->
<div id="product-review-container" data-role="product-reviews"></div>
<?= $block->getChildHtml() ?>

<script type="text/javascript">
require(['jquery', 'Ibapi_Multiv/js/jquery.blockUI'],function($){
$(function () {
	function processReviews(url, fromPages,s) {
	//	$.blockUI({message: '<?php echo __('..')?>'});
		$.ajax({
            url: url,
            cache: true,
            dataType: 'html',
            showLoader: false,
            loaderContext: $('.product.data.items')
        }).done(function (data) {
            s.data('shown',1);
            $('#product-review-container').html(data);
            $('[data-role="product-review"] .pages a').each(function (index, element) {
                $(element).click(function (event) { //eslint-disable-line max-nested-callbacks
                    processReviews($(element).attr('href'), true,s);
                    event.preventDefault();
                });
            });
        }).complete(function () {
           //// $.unblockUI();
            if (fromPages == true) { //eslint-disable-line eqeqeq
                $('html, body').animate({
                    scrollTop: $('#reviews').offset().top - 50
                }, 300);
            }
        });
    }

    processReviews('<?php echo $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>',false,$('#product-review-container'));

	$('#show-reviews').click(function (event) {
        var acnchor;
		
        event.preventDefault();
		if(!$(this).data('shown')){
			processReviews('<?php echo $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>',false,$(this));
			
			}	
        
    });
})

}
);
</script>
</div>