<div class="block-group box-section">	

<div class="line_bot">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_compte_premium')->toHtml(); ?>	
</div>		

	<div class="container">
		<!-- <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_static_h56')->toHtml(); ?>	-->
			
		<div class="blog-slider">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('sidebar/slider.phtml')->toHtml();?> 
		</div>
	</div>
</div>