<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
if($block->getCollection()):
	if($category != NULL):
		?>
		<?php if ($block->getCollection()->getSize()): ?>
			<div class="toolbar toolbar-products" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
				<?php if ($block->isExpanded()): ?>
					<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
				<?php endif; ?>

				<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

	<?php  if($block->canShowDate()): ?>
				<div  class="toolbaropts advopts">
				<?php  if($block->canShowSize()): ?>
				
				<div class="sizedialog">
				<p class="spnsz">
				<?php echo __('Tailles') ?>&nbsp;-
				</p>
				
				</div>
				<?php endif;?>
				<div  class="datedialog">
				<p>

				<span class="topbarperiod"><?php echo __('Période de location') ?>&nbsp;</span>

				<span class="spnsd"></span>
				<span class="topbarau">&nbsp;<?php echo __('au') ?>&nbsp;</span>
				<span class="spned"></span>
				
				</p>
				
				</div>
				
                </div>
				
	<?php endif; ?>


                	<?php echo $block->getPagerHtml() ?>



				<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

				<?php if ($block->isExpanded()): ?>
					<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
				<?php endif; ?>
			</div>
<?php endif;endif;endif;?>		
		