<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>


<?php $_product = $block->getProduct(); ?>



<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>



<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>

<input type="hidden" name="qty" value="1">      
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>




<?php endif; ?>







<script type="text/x-magento-init">
{
    "*": {
        "Ibapi_Multiv/js/addproduct": {
            "radioCheckboxClosest": ".nested"
        }

    }

}

</script>



