<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>

<?php// foreach ($detailedInfoGroup as $name):?>

<?php //endforeach;?>
        <?php $detailedInfoGroup=    ['product.attributes','product.info.description','size-grid-block','faqlist','size-grid-block2']?>
        <div class="collapsibleContainer" data-mage-init='{"accordion":{"openedState":"active","collapsible": true,"active":false,"multipleCollapsible": false}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div 
	                class="collapsibleTab"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <div data-role="trigger"
                       tabindex="-1"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </div>
                </div>
                <div class="collapsibleContent" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content" >
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
