<!-- <a href="http://beselective.be/fr/" class="action extra"><span>Extrabutton</span></a> -->



<a href="<?php echo $this->getUrl('showroom') ?>"><div class="box-tocart" style="float: left; padding-left: 23px;">
    <div class="fieldset">
        

            <div title="Essayage" class="action primary tocart">
                <img src="https://beselective.be/pub/media/wysiwyg/reassurance/essayage.png" style="width: 24px;line-height: 28px; padding-right: 2px; vertical-align: middle;" alt=""> <span style="font-size: 12px;font-weight: 600; margin-left: 3px;text-transform: uppercase;"><?php echo __('Essayage') ?></span>
            </div>

    </div>
</div>
</a>



