<?php 
	$helper = $this->helper('Netbaseteam\Faq\Helper\Data');
	$mostFaqData = $block->getMostFaqData();
?>
<div class="row">
	<h3 class="most-faq-title"><?php echo __('Most FAQ') ?></h3>
	<div class="most-faq-main">
		<?php if ($block->hasMostFaq()): ?>
			
			<?php foreach ($mostFaqData as $mostFaq): ?>
				<div class="panel">
					<div class="panel-heading">
						<h4 class="panel-title" >
							<i data-icon="fa-plus-square-o" data-icon-active="fa-minus-square-o" class="fa fa-plus-square-o"></i>
							<a href="javascript:void(0);"><?php echo __(strip_tags($mostFaq['question'])); ?></a>
						</h4>
					</div>
					
					<div class="panel-body">
						<div class="panel-content"><?php echo __($mostFaq['answer']); ?></div>
						<div class="more-info">
							<?php if ($helper->getShowFaqAthor()): ?>
								<?php if (!empty($mostFaq['author_name'])): ?>
									<span class="author">
										<?php echo __('Created by '.$mostFaq['author_name']);?>
									</span>
								<?php endif ?>
							<?php endif ?>

							<?php if ($helper->getShowFaqCreatedTime()): ?>
								<?php if (!empty($block->getFormatDate($mostFaq))): ?>
									<span class="created-time">
										<?php echo __('on '.$block->getFormatDate($mostFaq));?>
									</span>
								<?php endif ?>
							<?php endif ?>
						</div>		
					</div>
					
				</div>	
			<?php endforeach ?>
			
		<?php else: ?>
			<h4 class="non-most-faq"><?php echo __('No Most FAQ Result'); ?></h4>
		<?php endif ?>
	</div>
</div>
<div style="clear: both;"></div>
