<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
?>
<?php
/**
 * Blog post info template
 *
 * @var $block \Plazathemes\Blog\Block\Post\Info
 */
?>

<div class="spacer"></div>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-smb-12">
                <header class="group-title1">
                    <h4><?php $_post = $block->getPost() ?><h4>
                </header>
            </div>
            
        </div>
</div>


