<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Plazathemes\Blog\Block\Post\AbstractPost
 */
?>

<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $stringFilter = new \Magento\Framework\Stdlib\StringUtils;
?>
<li class="post-holder post-holder-<?php echo $_post->getId() ?>">
	<div class="col-sm-4 col-xs-12" style="height:450px;">
		<div>
			<div class="post-images">
				<a href="<?php echo $_post->getPostUrl() ?>">
					<img style="max-height:225px;" src="<?php echo $this->getMediaFolder().$_post->getThumbnailimage() ?>"/>
				</a>
			</div>
		</div>
		<div  style="padding-top: 20px">
			<div class="post-content" style="padding-bottom:25px;">
			<!--<?php echo $this->getInfoHtml() ?>-->
				<div class="post-title-holder clearfix" style="height:50px;">
					<h2 class="post-title" style="margin-bottom: -4px; margin-top: 15px, font-size: 16px; line-height: 18px;">
						<a class="post-item-link"
						   href="<?php echo $_postUrl ?>">
							<?php echo $_postName; ?>
						</a>
					</h2> 
				</div> 
				<div class="post-description clearfix"  style="height:50px; padding: 15px 0 18px; margin: 0; line-height: 24px; color: #707070; font-size: 12px;">
					<!--<?php echo $_post->getShortContent() ?>-->
					<?php echo $stringFilter->substr($_post->getShortContent(),0,220)." ..."; ?>
					
				</div>
				<!--<a class="post-read-more hidden-xs" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
				   Readmore
				
				<a class="post-read-more hidden-sm visible-xs" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
				   Readmore
				</a>-->
			</div> 
		</div>
	</div>
    

   
</li>