<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_PromotionBar
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
use Bss\PromotionBar\Model\Source\Position;

/**
 * Block
 *
 * @var $block \Bss\PromotionBar\Block\PromotionBar
 */
$page = $block->getBlockType();
$position = $block->getBlockPosition();
$storeViewId = $block->getStoreId();
$productId = $block->getProductId();
$categoryId = $block->getCategoryId();
$pageBottomPositon = ($position == Position::PAGE_BOTTOM)? "id='promotionbar_bottomposition'": "";
$postUrl = $block->getBaseUrl().'promotionbar/render/promotionbar';
?>

<div class="promotionbar_wrapper promotionbar_position_<?php echo $page.$position ?>"
    <?php echo $pageBottomPositon ?>>
</div>
