<footer class="footer-container">
	<div class="footer-top">
		
			<?php echo $this->getChildHtml('block_reassurance')?>
		
	</div>
	<div class="footer-top">
		<div class="container">
			<?php echo $this->getChildHtml('subscribe')?>
		</div>
	</div>
	<div class="footer-middle">
		<div class="container">
			<?php echo $this->getChildHtml('footer_static')?>
		</div>
	</div>
		<div class="footer-bottom">
			<?php echo $this->getChildHtml('footer_end_v2')?>
			<div id="back_top">
				Back to top
			</div>
		</div>
</footer>

<script type="text/javascript">
	require(["jquery"], function(jQuery){
		jQuery(window).scroll(function() {	
			if(jQuery(this).scrollTop() > 300) {
				jQuery('#back_top').fadeIn();   
			} else {
				jQuery('#back_top').fadeOut();
			}
		});
		   jQuery('#back_top').click(function() {
			jQuery('body,html').animate({scrollTop:0},500);
		});
		if (jQuery(window).width() < 992) {   
			jQuery('.footer-static .footer-static-title').click(function(){     
				jQuery(this).parent('.f-col').toggleClass('active').siblings().removeClass('active'); 
				jQuery(this).next('.f-col .footer-static-content').toggle(300);
				jQuery(this).parent('.f-col.active').siblings().children('.f-col .footer-static-content').slideUp(300); 
			}); 
			 
		}
	});
</script>